### ISSUE TITLE
Pandas error while backfilling with parquet

### ISSUE THREAD

**Issue by rbdm-qnt** [bmoscon/cryptostore#79] opened 2020-04-13 10:39 UTC
I configured my save interval to 900s and started a backfill using parquet files. Every time it tries to save it I get this error:

2020-04-13 12:41:18,190 : WARNING : Backfill - encountered error backfilling BITMEX - XBTUSD, trying again...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cryptostore/plugin/backfill.py", line 64, in _worker
    for t in r[exchange].trades(pair, str(seg_start), str(end)):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cryptofeed/rest/bitmex.py", line 179, in trades
    for data in self._get('trade', symbol, rest_start, end, retry, retry_wait):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cryptofeed/rest/bitmex.py", line 70, in _get
    dates.append(pd.Interval(left=API._timestamp(start_date), right=API._timestamp(end_date)))
  File "pandas/_libs/interval.pyx", line 309, in pandas._libs.interval.Interval.__init__
ValueError: left side of interval must be <= right side

while the live data gets saved just fine.

**Comment by rbdm-qnt** [comment] 2020-04-13 10:46
This was the last successful save:

2020-04-13 02:46:04,759 : INFO : Backfill - Starting for BITMEX - XBTUSD for range 2016-01-01 - 2020-04-13 00:31:00.024999095
2020-04-13 02:46:04,760 : INFO : Backfill - Reading 2020-04-13 00:00:00 to 2020-04-13 00:31:00.024999095 for BITMEX - XBTUSD
2020-04-13 02:51:20,273 : INFO : Backfill - Wrote 2020-04-13 00:00:00 to 2020-04-13 00:31:00.024999095 for BITMEX - XBTUSD
2020-04-13 02:51:20,274 : INFO : Backfill - Reading 2020-04-12 00:00:00 to 2020-04-12 23:59:59.999999999 for BITMEX - XBTUSD


And this was the first failed save:

2020-04-13 03:42:30,471 : INFO : Backfill - Wrote 2020-04-12 00:00:00 to 2020-04-12 23:59:59.999999999 for BITMEX - XBTUSD
2020-04-13 03:42:30,472 : INFO : Backfill - Reading 2020-04-11 00:00:00 to 2020-04-11 23:59:59.999999999 for BITMEX - XBTUSD
2020-04-13 03:42:41,334 : WARNING : Backfill - encountered error backfilling BITMEX - XBTUSD, trying again...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cryptostore/plugin/backfill.py", line 64, in _worker
    for t in r[exchange].trades(pair, str(seg_start), str(end)):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cryptofeed/rest/bitmex.py", line 179, in trades
    for data in self._get('trade', symbol, rest_start, end, retry, retry_wait):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/cryptofeed/rest/bitmex.py", line 70, in _get
    dates.append(pd.Interval(left=API._timestamp(start_date), right=API._timestamp(end_date)))
  File "pandas/_libs/interval.pyx", line 309, in pandas._libs.interval.Interval.__init__
ValueError: left side of interval must be <= right side

Then this last one repeated over and over again for the whole night, and I only have 1 correctly saved backfill parquet from the first time it executed correctly

**Comment by rbdm-qnt** [comment] 2020-04-13 23:47
Update! 
I tried deleting influx, deleting all parquet files and restarting everything. Now it will save the live data correctly as it did before, it will print this without any error, but it won't save files from the backfill:

2020-04-14 00:55:24,861 : INFO : Backfill - Starting for BITMEX - XBTUSD for range 2016-01-01 - 2020-04-13 22:40:15.941998912
2020-04-14 00:55:24,861 : INFO : Backfill - Reading 2020-04-13 00:00:00 to 2020-04-13 22:40:15.941998912 for BITMEX - XBTUSD

**Comment by bmoscon** [comment] 2020-04-15 00:41
dupe of #73

**Comment by rbdm-qnt** [comment] 2020-04-15 01:50
> dupe of #73

Sorry didn't see that. However, the problem solved itself. After I restarted the system it pulled 1D of historical, then nothing (just live data) for about 1.30h, then it pulled 2 more days of data, then nothing again for about 40 minutes, and then it started pulling data very fast, and backfilled 4 years in 3 hours. Kinda odd, but it worked! Thanks

**Comment by bmoscon** [comment] 2020-08-01 17:33
the reason it was slow then fast is that for older historical data (older than 24-36 hours) it can and will pull it directly from the AWS bucket, but for recent data it has to go through the bitmex API which is slow.

**Closed by bmoscon** 2020-08-01 17:33 UTC
