### ISSUE TITLE
too much files with storage=parquet, each interval for each backend separately is needed

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#19] opened 2019-07-22 15:35 UTC
storage with parquet.
If I have 50 pairs, and storage_interval/duration = 60s by default, there will be  50 * 60 = 3000 files per hour.
there files just locate in the same folder with my customized_config.yaml

this is because storage_interval=60 is good for influxdb/arctic, but too frequent for parquet as files in the disk.

they should use different **storage_interval**

**Comment by bmoscon** [comment] 2019-07-24 00:07
@xiandong79 good issue, I'll look into letting the user specify each interval separately.

**Comment by xiandong79** [comment] 2019-08-01 02:07
I have notice that "Allow user to specify book specific options like deltas, depths, inte..." 
**Great work! and Design!!** .  

It would be great that use can specify **different storage_interval** for different persistent storage type.

**Comment by bmoscon** [comment] 2020-02-29 01:57
Going to handle this and some other things as part of #56 so closing while I work on that issue

**Comment by bmoscon** [comment] 2020-03-01 01:11
this part of the issue is done/merged

**Comment by bmoscon** [comment] 2020-04-16 16:55
reopening because specifying a storage interval per storage type is not supported yet

**Comment by yohplala** [comment] 2020-08-30 19:44
Albeit feature not implemented, problem is normally solved with PR #110.

**Comment by bmoscon** [comment] 2020-09-18 20:01
I'm going to mark this as closed - #111 fixes the original issue

**Closed by bmoscon** 2020-09-18 20:01 UTC
Labels: Feature Request, Partially Complete
