### ISSUE TITLE
Message length too long, dropping. for BITMEX using cryptostore 0.1.0

### ISSUE THREAD

**Issue by xiandong79** [bmoscon/cryptostore#24] opened 2019-07-26 06:21 UTC
2019-07-26 14:16:46,769 : ERROR : BITMEX: Error message from exchange: {'status': 400, 'error': 'Failed to decode incoming data: Message length too long, dropping. Please see the documentation at https://www.bitmex.com/app/wsAPI.', 'meta': {}}

with following in config.yaml:
```
cache: redis

exchanges:
    BITMEX:
        l2_book: [XBTUSD, ETHUSD, XRPU19, BCHU19, ADAU19, EOSU19, TRXU19, XBTU19, XBTZ19, ETHU19, LTCU19]
        l3_book: [XBTUSD, ETHUSD]
        trades: [XBTUSD, ETHUSD, XRPU19, BCHU19, ADAU19, EOSU19, TRXU19, XBTU19, XBTZ19, ETHU19, LTCU19]

storage: [influx, parquet]
```

**cryptostore 0.1.0
cryptofeed 1.0.0**

**Comment by xiandong79** [comment] 2019-07-26 07:07
Actually， in cryptofeed 1.0.0

in cryptofeed/examples/demo_book_delta.py, you can see another error message.

```py
def main():
    f = FeedHandler()
    f.add_feed(Bitmex(pairs=['XBTZ19'], channels=[L2_BOOK], callbacks=DeltaBook("Bitmex").L2))
    f.run()
```

**Comment by xiandong79** [comment] 2019-07-26 07:12
The error is possible in `XBTZ19`

**Comment by bmoscon** [comment] 2019-07-26 23:51
Bitmex cant handle the size of the subscription message. You're subscribing to too many datapoints on a single websocket. I'll update the code to do a feed per datatype (book, trade, etc) and this should fix the issue

**Comment by bmoscon** [comment] 2019-08-12 23:28
this is a pretty big change, so I will do it, but it may be another week or two until I get to it

**Comment by xiandong79** [comment] 2019-08-14 09:02
In feedhandler.py, for **Gemini** exchange, each pair would launch a new feed.
what about the solution of **Bitmex** just **copies** the solution of Gemini?  launch a new feed for every 5 pairs? 

Would this method be feasible and cost less reconstruction?

**Comment by bmoscon** [comment] 2019-09-11 23:26
should be fixed now. I start a separate feed per channel (feed, book, etc) so the message size should be much less for each subscription now.

**Closed by bmoscon** 2019-09-11 23:26 UTC

**Comment by xiandong79** [comment] 2019-09-12 02:37
Will test it today.

**Comment by jeffneuen** [comment] 2020-03-14 18:03
@bmoscon I am still seeing this exact issue, using cryptostore and cryptofeed. I'm running cryptostore using the provided Dockerfile, so it is pulling cryptofeed from master.

I *think* that the problem is coming from the subscribe function in https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/exchange/bitmex.py, line 476. Would you be interested in a PR that attempts to split up long subscriptions into multiple subscribe requests? I'd try to do this by executing multiple websocket.send commands containing the split-up subscriptions.

**Comment by bmoscon** [comment] 2020-03-14 18:20
Theres definitely a limit to the size of the data coming back, so it would need to be subset further. I'll definitely accept a PR. I assume you'd handle this on the cryptostore side and not the cryptofeed side?

**Comment by jeffneuen** [comment] 2020-03-14 22:08
I thought I would just try fixing it on the cryptofeed side, and do it in a way that the cryptostore side wouldn't have to change, but I'll have to dive into the internals a little more first. Also, then cryptofeed-only users could benefit as well. Do you see an advantage to fixing it on the cryptostore side?

I haven't experienced the size limit on the return data, but if so, I'll explore ways to handle that as well.

**Comment by bmoscon** [comment] 2020-03-15 13:34
You could increase the message size the websocket library uses (i've done that a few times already) but its pretty inefficient for smaller messages, only the initial large message needs it (with the full book). I dont think you can fix it on the cryptofeed side without introducing behavior thats less than ideal for a library. If you start breaking everything up into independent subscriptions, you may his message limits on subscription messages, you'd be unable to pair chatty subscriptions with quieter ones (and would hit no received message timeouts), etc. These are odd behaviors that shouldnt happen unbeknownst to the user, the user should have pretty granular control over what happens - doing this on the cryptofeed side would break this. 

The max message size is about 8MB: https://github.com/bmoscon/cryptofeed/blob/master/cryptofeed/feedhandler.py#L195

I'd be curious to know how large a message you're receiving, so we could consider adjusting this. 16MB doesnt seem unreasonable

**Comment by jeffneuen** [comment] 2020-03-16 02:55
In the past, I've had decent luck with just making multiple subscriptions requests on the same websockets connection. The biggest issue I ran into there was when I tried to make each request individually, and hit rate limits, so I just added delays to compensate. That approach also has the advantage that the big initial first book messages don't come batched in one message. What do you think about that approach, but implemented in cryptostore? I do see your point that behavior like this might be unexpected in cryptofeed.

**Comment by bmoscon** [comment] 2020-12-12 17:38
@jeffneuen just as an FYI - I've fixed this issue in Crytpofeed. The fix will work for cryptostore as well, no change needed on that side. It will be pushed today (doing more testing on my code)

**Comment by jeffneuen** [comment] 2020-12-15 03:32
@bmoscon awesome, thanks! Will give this is a look!
