### ISSUE TITLE
okcoin change into okex！

### ISSUE THREAD

**Issue by otccoin** [bmoscon/cryptostore#37] opened 2019-08-15 18:38 UTC
okcoin change into okex！

**Comment by bmoscon** [comment] 2019-08-15 23:22
Not sure what this means.

**Comment by otccoin** [comment] 2019-08-16 08:54
www.okex.com

**Comment by bmoscon** [comment] 2019-08-17 01:12
yeah, cryptofeed supports both. okex and okcoin.

**Comment by bmoscon** [comment] 2019-08-18 21:50
there isnt enough information for me to discern what the issue is - so closing. feel free to re-open when/if you can supply more information

**Closed by bmoscon** 2019-08-18 21:50 UTC
