### ISSUE TITLE
Support book_intervals on snapshots without deltas

### ISSUE THREAD

**Issue by mschneider** [bmoscon/cryptostore#117] opened 2020-10-02 11:44 UTC
book_interval config variable is apparently ignored when not fetching book_deltas. I used the following config to store L2 snapshots. Looking at the code book_interval seems only considered in the `book_delta = True` code path.

```
    KRAKEN:
        l2_book:
            symbols: [BTC-USD, ETH-USD, ETH-BTC]
            max_depth: 16
            book_delta: false
            book_interval: 1000
```

Expected behavior: Store one order book snapshot per symbol per second
Current behavior: Store every order book change, stores more than 10 snapshots per symbol per second

**Comment by bmoscon** [comment] 2020-10-02 12:31
If this is a bug, its only a bug in the documentation - its working as intended. book interval only applies when book deltas are enabled. If this is a feature you want, I can change the label, otherwise I'll just update the comments in the config file to be clearer and close this.

**Comment by mschneider** [comment] 2020-10-02 13:30
Yeah, wasn’t sure about this being a feature or a bug. Definitely would be
happy if you could track this as a feature request :)

**Comment by bmoscon** [comment] 2020-10-04 00:29
Support for this has been added in cryptofeed - just need to add support for it here now

**Comment by bmoscon** [comment] 2020-10-10 00:53
ok, i've added this, its called `snapshot_interval`

**Closed by bmoscon** 2020-10-10 00:53 UTC
Labels: Feature Request
